# Generated by Django 5.1.6 on 2025-03-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_comments_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
