# Generated by Django 5.1.6 on 2025-03-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='data',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
