# Generated by Django 5.1.6 on 2025-03-25 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_review_data_alter_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='data',
        ),
    ]
