# Generated by Django 5.1.6 on 2025-04-04 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('num_floors', models.IntegerField()),
                ('has_pit', models.BooleanField()),
                ('num_kitchens', models.IntegerField()),
                ('central_ac', models.BooleanField()),
                ('num_washers', models.IntegerField()),
                ('num_dryers', models.IntegerField()),
                ('elevator', models.BooleanField()),
                ('gender_specific', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('floor', models.IntegerField(editable=False)),
                ('num_occupants', models.IntegerField()),
                ('floor_bathrooms', models.IntegerField()),
                ('srd', models.BooleanField()),
                ('internal_bathroom', models.BooleanField()),
                ('kitchen', models.BooleanField()),
                ('common_room', models.BooleanField()),
                ('avg_rating', models.FloatField(default=0.0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='browse.building')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('building', 'number'), name='unique room in building')],
            },
        ),
    ]
