# Generated by Django 5.1.6 on 2025-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='sub_free',
            field=models.BooleanField(default=False),
        ),
    ]
