# Generated by Django 5.1.6 on 2025-04-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_building_sub_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='window_direction',
            field=models.IntegerField(choices=[(0, 'North'), (1, 'South'), (2, 'East'), (3, 'West')], default=0),
        ),
    ]
