# Generated by Django 5.1.6 on 2025-04-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_room_window_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='region',
            field=models.CharField(choices=[('N', 'North'), ('E', 'East'), ('S', 'South'), ('O', 'Off-Campus')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='num_occupants',
            field=models.IntegerField(choices=[(1, 'Single'), (2, 'Double'), (3, 'Triple'), (4, 'Quad'), (5, 'Five-man'), (6, 'Six-man'), (7, 'Seven-man')], default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='window_direction',
            field=models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], default='N', max_length=1),
        ),
    ]
