# Generated by Django 5.1.6 on 2025-04-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0004_alter_building_region_alter_room_num_occupants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(choices=[(0, 'Pit'), (1, 'First Floor'), (2, 'Second Floor'), (3, 'Third Floor'), (4, 'Fourth Floor')], default=0, editable=False),
        ),
    ]
