# Generated by Django 5.1.6 on 2025-04-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0005_alter_room_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='central_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='gender_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='has_pit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='num_dryers',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='building',
            name='num_floors',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='building',
            name='num_kitchens',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='building',
            name='num_washers',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='common_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor_bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='internal_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(default=1111),
        ),
        migrations.AlterField(
            model_name='room',
            name='srd',
            field=models.BooleanField(default=False),
        ),
    ]
