# Generated by Django 5.1.6 on 2025-04-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0006_alter_building_central_ac_alter_building_elevator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='ca',
            field=models.BooleanField(default=False),
        ),
    ]
