# Generated by Django 5.1.6 on 2025-04-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0007_room_available_room_ca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='common_room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='window_direction',
        ),
    ]
