# Generated by Django 5.1.6 on 2025-05-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0008_remove_room_common_room_remove_room_window_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='multi_room',
            field=models.BooleanField(default=True),
        ),
    ]
