# Generated by Django 5.1.6 on 2025-04-16 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0007_room_available_room_ca'),
        ('review', '0003_review_created_time_review_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'room'), name='unique_user_review_of_room'),
        ),
    ]
