# Generated by Django 5.1.6 on 2025-02-18 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cluster', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('num_floors', models.IntegerField(default=0)),
                ('has_pit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(editable=False)),
                ('number', models.IntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='browse.building')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('building', 'number'), name='unique_room_in_building')],
            },
        ),
    ]
