# Generated by Django 5.1.6 on 2025-03-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
