name: Server Health Check

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes

jobs:
  check-toggle:
    runs-on: ubuntu-latest
    steps:
      - name: Check Server Status
        run: |
          URL=""  # Change to our server URL
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" $URL)
          
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Server is DOWN! HTTP Status: $STATUS_CODE"
            exit 1
          else
            echo "Server is UP! HTTP Status: $STATUS_CODE"
          fi